Issues/#3
y-iwamoto/twitter-cloneapp pull request #17
Opened 2017-09-13 10:40 UTC by y-iwamoto

ユーザアカウント画面のレビューをお願いいたします

2017-09-13 14:30 UTC, NaitoYuki reviewed
@y-iwamoto 
routes.rbは修正していませんか？
今のコミットされている内容だけだと、アカウントの画面に遷移できないです。

2017-09-13 21:33 UTC, y-iwamoto commented
コミット漏れリソースがありましたので、またご確認お願いいたします。
途中pushした際に、エラーが出てMerge branch...と２つ出てしまっています。
サイト見ながらやって見ましたが、上手くいってなければ、ご指摘お願いいたします。

2017-09-14 04:12 UTC, NaitoYuki requested changes
databaseconfig/database.yml
は削除しないでください。
それがあればこちらで動かせそうです！

2017-09-14 21:14 UTC, y-iwamoto commented
すいません。何かのネットの記事で、database.ymlはコミットしない内容があったので、それに右倣えしていました。パスワード部分のみ変更していただく形の、sample用のdatabase.ymlを用意いたしましたので、ご確認お願いいたします

2017-09-15 02:56 UTC, merged